/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Name]
      ,[Surname]
      ,[Phone]
      ,[Gender]
      ,[Seat Number]
      ,[Price]
      ,[From]
      ,[To]
      ,[Date]
  FROM [BTSP].[dbo].[Table_1]